### ISSUE TITLE
Defaul reconnection settings and self-disposing connection

### ISSUE THREAD

**Issue by Zetanova** [AkkaNetContrib/Akka.Persistence.EventStore#12]
the EventStore default reconnection settings are
MaxReconnections=10
ReconnectionDelay=100ms
ConnectionTimeout=1sec

If the eventstore server is unreachable over ~11sec (10 retries * (1sec timout + 100ms backoff))
then the ```IEventStoreConnection.Closed``` EventHandler gets fired. 

After the Closed-Event the connection instance disposes itself 
and all new method calls to the instance will throw ObjectDisposedException. 
The connection instance is unrecoverable at this point.

Currently the ```IEventStoreConnection.Closed``` EventHandler is not used 
and this leads to stuck/allways throwing Akka.Persistence plugin.

A workaround would be to set an infinit reconnection retry count with the connectionString:
MaxReconnections=-1; ReconnectionDelay=1000;

I would make a PR but i dont know how ```AsyncWriteJournal``` should behave for recovery.

Should AsyncWriteJournal and SnapshotStore stop itself to get restarted and be recovered?

**Comment by alexpacer** [comment]
Hi @Zetanova I'm not sure if my error is related to this issue

I've a Singleton Actor and made it persistent using Event store, It's been running okay for 2 weeks and then this error appeared 

> Object name: 'Akka-Store'.
   at Akka.Persistence.EventStore.Journal.EventStoreJournal.WriteMessagesAsync(IEnumerable`1 atomicWrites)
[15:40:44 ERR] Rejected to persist event type [Common.Messages.Events.AddToShelfRequestedEvt] with sequence number [18882] for persistenceId [shelf] due to [Cannot access a disposed object.

I was connecting to EventStore with only ConnectTo=<server> 

I'm trying to change my connection string to add your walk around and seeing if this error ever occured again.

**Comment by Zetanova** [comment]
@alexpacer  yes this is the problem

add the parameter to the connection string to workaround the issue. 
Add `MaxReconnections=-1; ReconnectionDelay=1000;`

**Comment by Zetanova** [comment]
Even with the setting MaxReconnections=-1; ReconnectionDelay=1000; 
Sometimes on load the EventStore connection closes with:
```
Akka.Persistence.EventStore.Common.SubscriptionDroppedException: Subscription dropped due reason ConnectionClosed
 ---> EventStore.ClientAPI.Exceptions.ConnectionClosedException: Connection was closed.
   --- End of inner exception stack trace ---
```

After that the whole EventStoreReadJournal is unrecoverable,
A new readJournal.EventsByTag will just deliver no elements.

**Comment by Zetanova** [comment]
The issue that the journal locks and is unrecoverable still happens when the eventstore restarts and/or is not reachable for a longer period. Maybe it happens when the dns name is only resolvable after the first use of the journal.

**Comment by mjaric** [comment]
Hi @Zetanova, sorry for delayed response. Can you please tell me do you use EventstoreReadJournal?

**Comment by Zetanova** [comment]
@mjaric  Yes, i am using  EventstoreReadJournal
