### ISSUE TITLE
Updating to gRPC client, and support EventStore 20

### ISSUE THREAD

**Issue by ptjhuang** [AkkaNetContrib/Akka.Persistence.EventStore#18]
Placeholder for a relatively big PR - we're 90% done.

Just wanted to know if people want this:

1) a huge change, break backwards compatibility, only works with EventStore 20, or
2) branch, and keep the new branch on old ES, default branch on ES 20 (it's what ES client project has done)
3) in a separate Akka contrib project altogether
4) spend time to make plugin compatible with both ES 5 and ES 20 (in which case, I need someone help - don't have bandwidth at the moment to do this)

**Comment by ismaelhamed** [comment]
@ptjhuang any update on the gRPC support for this plugin? Are you guys still working on it?

**Comment by ptjhuang** [comment]
We almost took it to alpha, but for our use case, we found the tooling too limiting, and there were too many niggly things like the offset of 0 being inconsistently used as start-of-stream in the EventStore driver.  Long story short, we switched to using Mongo.

The fork is here if someone wants to take it over so it wouldn't be a complete waste.
https://github.com/ptjhuang/Akka.Persistence.EventStore/tree/dev

We wrote a firehose Akka Stream Source stage because the gRPC subscription API doesn't backpressure, and couldn't find an existing one around.  It could be useful for other projects.

A recent version of EventStore changed its JavaScript engine, and so has a breaking change which wasn't well documented, and that still requires this plugin to catch up on: it no longer supports string metadata - has to be JSON object.  This I believe is incompatible with the Akka persistence specs, so the tests will fail without overrides.  To get around this issue, we gave up and moved it into our own project to move things faster.

**Comment by ismaelhamed** [comment]
@ptjhuang thanks for detailed response! Looks like it's more work that it might be worth. Out of curiosity, how is Mongo performing for you guys?

**Comment by ptjhuang** [comment]
Big question - one we spent a lot of time working through.

We generally found MongoDB performed consistently for us, and better than EventStore for our use cases - high actor numbers with low event count.  This usage pattern seems to be taxing for EventStore.  We also needed projections to separate the global event stream into tenant-scoped streams slowing it down.  For MongoDB, that's just an index and it performs very well for us.

But what sealed the deal for us with Mongo are these points:

* We can take backups and restores with MongoDB, which happens at file level, as opposed to at application level for EventStore, so Mongo is order of magnitudes faster for our use case.
* Event import directly into the event journal in Mongo is much faster than writing to EventStore using their respective drivers. Possibly because the above projections needs to run. (see https://replicator.eventstore.org/docs/limitations/ - their own data moving utility says 150-300 events/sec for single writer)
* We wanted the concept of databases for isolation - we customised the MongoDB plugin to split events into different databases (tenant-scoped), which gives us another scaling point.

When we did do benchmarks, 10k actors 2 messages each, we got 2.8k events/sec write in a single node dev environment for MongoDB.  EventStore was around 2.5k events/sec write when we enabled enough projections to make the data useful for us.

Do you have any experience to share?

**Comment by ismaelhamed** [comment]
We've only relied on Sql plugins (SQL Server and Oracle) so far, and they've performed remarkable well given the various workloads that are required for our business. But the setups for deployments with millions of persistent actors (i.e., representing IoT devices) are becoming beefier and beefier every time (so much that some customers are also required to adquire SQL Server Enterprise licences).

Therefore, I'm currently in the hunt for alternative datastores. I've been looking into EventStore because it was precisely built for Event Sourcing, and Akka's Persistence is the current workload we're looking to move out of the RMDBs. 

We have no experience with Mongo either, but the ability to create a sharded cluster seems like (at least on paper) it could definitively help.

@Aaronontheweb , in the JVM the Cassandra plugin seems like the safest bet when it comes to big setups and deployments. I'd say we need a safe default bet too in Akka.NET

**Comment by Aaronontheweb** [comment]
The Akka.Persistence.Cassandra plugin hasn't been touched since 2015 - so I'm certain it's out of date both with Akka.Persistence but also with Cassandra itself.

Speaking from my experience using it (tens of millions of active FSMs processing hundreds of millions of real-time events per day) even 10 years ago, it's a great fit for Akka.Persistence at scale. It's somewhat expensive to operate since you really need a minimum of 4 nodes in order to satisfy the recommended replication factor (RF=3 by default) but if you're at that level of traffic then it makes perfect sense. There are also serverless options for hosting Cassandra and some Kubernetes-friendly Cassandra packages now that should make it easier to host at smaller scales than previously.

We'd need to do a major overhaul of the Akka.Persistence.Cassandra plugin to make it workable; we're much better at integration testing persistence plugins than we used to be (thanks to the prevalence of Docker since then) so I don't think it would be insurmountable to do that. Let me know if you're interested.

**Comment by ismaelhamed** [comment]
> We'd need to do a major overhaul of the Akka.Persistence.Cassandra plugin to make it workable; we're much better at integration testing persistence plugins than we used to be (thanks to the prevalence of Docker since then) so I don't think it would be insurmountable to do that. Let me know if you're interested.

I'll give it a shot to the Mongo plugin. But IMO, a revamped Cassandra plugin would be a nice addition to the New Year's resolutions for 2022 ;)

**Comment by Aaronontheweb** [comment]
Solved via https://github.com/akkadotnet/Akka.Persistence.EventStore/pull/19
